# netlify.toml
[build]
  command = "npm run build" # Or whatever command builds your frontend
  publish = "dist"          # Or whatever directory your built frontend goes into

[functions]
  directory = "functions"   # This tells Netlify where to find your functions
  node_bundler = "esbuild"  # Recommended for faster builds and smaller function sizes

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true # Ensures this redirect takes precedence