# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/:name"
  to = "/.netlify/functions/api-:name"
  status = 200
  force = true